# Generated by Django 2.1 on 2019-02-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacktypes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='teacher_name',
            field=models.CharField(choices=[('strm', 'Prof. R.K. Singh'), ('bd', 'Dr. Arun Sharma'), ('scse', 'Ms. Charu Gupta'), ('ads', 'Mr. Rishabh Kausal'), ('cpa', 'Dr. Mohona Ghosh'), ('cn', 'Mr. Gaurav Indra'), ('tp', 'Dr. Sourabh Bharti')], default='---------', max_length=100),
        ),
    ]
