# Generated by Django 2.1 on 2019-02-07 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedbacktypes', '0002_question_teacher_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(choices=[('strm', 'Prof. R.K. Singh'), ('bd', 'Dr. Arun Sharma'), ('scse', 'Ms. Charu Gupta'), ('ads', 'Mr. Rishabh Kausal'), ('cpa', 'Dr. Mohona Ghosh'), ('cn', 'Mr. Gaurav Indra'), ('tp', 'Dr. Sourabh Bharti')], default='---------', max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='teacher_name',
        ),
    ]
